### ISSUE TITLE
Globbing patterns for sub-projects

### ISSUE THREAD

**Issue by OliverJAsh** [gruntjs/grunt-contrib-compass#15]
I have several sub-projects that I want to run against a single Gruntfile, as they all need the same tasks running against them. For example, I need to compile the Sass using Compass in each sub-project.

I have tried globbing patterns:

```
compass: {
  options: {
    sassDir: './bundles/*/public/styles',
    cssDir: './bundles/*/temp/styles'
  }
}
```

But I get the following error:

```
Running "compass" (compass) task
Errno::ENOENT on line 441 of /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/pathname.rb: No such file or directory - /Users/Oliver/Development/Personal/Reader/bundles/*
Run with --trace to see the full backtrace
```

Suggesting I cannot use globbing patterns in this way with grunt-contrib-compass.

**Comment by morganhein** [comment]
I understand this is closed, however maybe it can now be re-opened as this is a possible re-occurring issue as the MEANjs generator for yo has multiple stylesheet folders by default. In fact, it seems that Angularjs and some major projects are moving to the "modules" format for each individual part of an app, with each module having it's own stylesheet folder.  

You can read about it [here](http://meanjs.org/docs.html#angularjs-modules)
