### ISSUE TITLE
Import Path - Incorrect Argument

### ISSUE THREAD

**Issue by brycejacobs** [gruntjs/grunt-contrib-compass#169]
Can be easily fixed by having a config.rb, but thought I would mention when using "importPath" in grunt config an error is thrown.

Error: invalid option: --import-path

Seems "-I IMPORT_PATH" is the correct syntax.

Compass 0.12.2
grunt-contrib-compass: 0.8.0

**Comment by mhluska** [comment]
I'm facing the same issue. This seems to be gone in master now: https://github.com/gruntjs/grunt-contrib-compass/blob/master/tasks/lib/compass.js#L198

**Comment by rstuven** [comment]
It was removed here :(
https://github.com/gruntjs/grunt-contrib-compass/commit/adc77b7ae5ca88d9dc36846b4b792c973b751dee

**Comment by rstuven** [comment]
Anyway, the error is gone after updating compass to the latest version. :)
