### ISSUE TITLE
http_path wrongly added to list of restricted CLI parameters 

### ISSUE THREAD

**Issue by arminrosu** [gruntjs/grunt-contrib-compass#190]
Hey all,

I wanted to transfer some settings into grunt but grunt-contrib-compass is blocking me from using `http_path` with `config`. Running `compass compile -c config.rb --http-path /hello` works.

Could it be it had been added to the [raw options](https://github.com/gruntjs/grunt-contrib-compass/blob/master/tasks/lib/compass.js#L24) by mistake?

This is what my `config.rb` looks like:

```ruby
# Directories
public_path = "build"
sources_path = "src"
project_path = File.expand_path(File.dirname(__FILE__))

css_dir = public_path + "/css"
fonts_dir = public_path + "/fonts"
generated_images_dir = public_path + "/images"
images_dir = public_path + "/images"
javascripts_dir = public_path + "/js"
sass_dir = sources_path + "/sass"
sprite_load_path = project_path + "/" + sources_path + "/sprites"

# URL
if http_path.nil?
    base_path = "/fallback"
else
    base_path = http_path
end

http_path = base_path
http_fonts_path = base_path + "/fonts"
http_generated_images_path = base_path + "/images"
http_images_path = base_path + "/images"

# OUTPUT
output_style = :compressed
environment = :production
sass_options = { :debug_info => false }
line_comments = false
```

**Comment by sindresorhus** [comment]
Not a mistake as it were introduced after this task was made: https://github.com/Compass/compass/commit/85d383e7c24671b39adc150212f8e44d35a8e6bc
