### ISSUE TITLE
Task fails if POSIXLY_CORRECT is in the environment

### ISSUE THREAD

**Issue by phadej** [gruntjs/grunt-contrib-compass#201]
The example test is in https://github.com/phadej/grunt-contrib-compass/tree/posixly-correct branch
![screen shot 2014-09-16 at 19 56 54](https://cloud.githubusercontent.com/assets/51087/4291212/8ae5f5ae-3dc2-11e4-8ccf-7d8b3e6c7604.png)

**Comment by sindresorhus** [comment]
Submit another PR and I'll accept...
