### ISSUE TITLE
grunt compass:dist "Aborted due to warnings" on jenkins build

### ISSUE THREAD

**Issue by Avien** [gruntjs/grunt-contrib-compass#210]
Hi 
I get the message during grunt task "concurrent:dist" (doing only "compass:dist" ) in jenkins build on Ubuntu 12.04
I dont see any error , only Use --force to continue

I have tried everything, including installing ruby 1.8.7/2.0.0 compass 0.12.7, 0.12.2 or 1.01 & sass 3.2.19/14/3.4.6
Nothing is working
On the other hand on my development machine macbook pro I have installed:
ruby 2.0.0p451, compass 0.12.2 & sass 3.2.14 and "concurrent:dist" working well

Help please
Thanks

**Comment by alexandarp** [comment]
+1, I'm also having this issue
