### ISSUE TITLE
Unable to disable sourcemap generation when specify option is used

### ISSUE THREAD

**Issue by dw72** [gruntjs/grunt-contrib-compass#211]
When I use specify option to exclude some sass files from processing, then sourcemaps are always generated. I try to specify sourcemap: false option and sourcemap=false in config.rb without effect.

When I remove specify option sporcemaps works as expected.

**Comment by peschee** [comment]
I'm experiencing the same issue. Is there a related issue or maybe a quick fix?

**Comment by maciej-gurban** [comment]
+1

This issue has been up for quite a while, without any resolution in sight. If you don't have enough time to look into it, please provide any pointers about where the issue could be. Thanks.

**Comment by maciej-gurban** [comment]
**Continue below for a solution**

I needed a fix to output a production-ready style.css, without it linking to the source map file, and all CSS minified. Passing just the options didn't make any different. Here's an excerpt from my Gruntfile.js:
````javascript
compass: {
    prod: {
        options: {
            sassDir: ['src/stylesheets'],
            cssDir:  ['src'],
            sourcemap: false,
            environment: 'production'
        }
    }
}
````
And here's how to fix it:
In order for these options to execute, you need to run compass with `--force` parameter. As a temporary solution, open up file under `node_modules/grunt-contrib-compass/tasks/compass.js` in your project's directory, and the find line containing
`compile(args, function () {`

Then, create a new line just before it, and paste:
`args.push('--force');`

And, that's about it. Now run your grunt task and enjoy.

**Comment by peschee** [comment]
@vladikoff Has this issue been solved? Do you have a commit reference?
