### ISSUE TITLE
Individual stylesheets must be in the sass directory

### ISSUE THREAD

**Issue by numediaweb** [gruntjs/grunt-contrib-compass#223]
Trying to specify some files in to be compiled but I get this error;

`Individual stylesheets must be in the sass directory`

My Gruntfile.js is like;
```js
compass: {
	'dev': {
		options: {
			force: true,
			sassDir: '<%= srcFolder %>scss',
			specify: ['<%= srcFolder %>scss/uiws.scss'],
			cssDir: '<%= destFolder %>assets/css',
			outputStyle: 'expanded',
		}
	}
}
```

In my scss folder I have 2 files `uiws.scss` and `other.scss`; if I remove the `specify: ['<%= srcFolder %>scss/uiws.scss'],` line, I get two files compiled without errors.. 

So how could I get the compass task to compile the `uiws.scss` file.

Thanks

**Comment by sindresorhus** [comment]
Not sure why you opened an issue here as it clearly a Compass bug.
