### ISSUE TITLE
Adding post fix to the generated css file for cache busting

### ISSUE THREAD

**Issue by vladyn** [gruntjs/grunt-contrib-compass#227]
Hello everyone, 
how can add a css pre- post- fix for cache busting. Instead of cssDir? 
I want the output file to have post-fix with variable from my package.json like version for example.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
