### ISSUE TITLE
Watching several directories with the `watch` option

### ISSUE THREAD

**Issue by TxHawks** [gruntjs/grunt-contrib-compass#229]
Is it possible to watch several directories using the `watch` configuration option?

My project's has sass files that I wan to watch for changes in the following structure:

```
 root
|__ bower_components
|  |_[direcotories with sass files]
|__ sass
|  |_[direcotories with sass files]
```

And sass partials are `@impor`ted from sub directories of `bower_component`.
The `sassDir` option is pointing to the `sass` directory, and  I am currently polling both directories for changes using `grunt-contrib-watch` to run the `compass` task whenever needed.
For performance reasons, I'd like to use the `watch` option in conjunction with `grunt-concurrent`, but couldn't figure out a way to watch several folders. Is that possible?

**Comment by sindresorhus** [comment]
This task is just a wrapper for Compass. Any question you have with this plugin is a general question about Compass and better asked on the Compass issue tracker or StackOverflow.
