### ISSUE TITLE
Compiling fails on latest update.

### ISSUE THREAD

**Issue by mkilpatrick** [gruntjs/grunt-contrib-compass#232]
When running the following grunt task I get the error "You must compile individual stylesheets from the project directory."

compass:
      compile_all:
        options:
          sassDir: "sass"
          cssDir: ".tmp/css_staging"
          spriteLoadPath: "sprites"
          generatedImagesDir: ".tmp/sprites/images"
          specify: ["**/vendor.scss", "**/default.scss"]
          relativeAssets: false
          assetCacheBuster: false
          raw: "Sass::Script::Number.precision = 10\n"
          bundleExec: true
          sourcemap: true

This works fine in 1.0.1 but fails in 1.0.2.

**Comment by Irmiz** [comment]
It fails when using `specify` option

**Comment by adamj88** [comment]
Getting the same error as well (without the specify option):

```
Running "compass:live" (compass) task
Verifying property compass.live exists in config...OK
File: [no files]
Options: httpPath="http", cssDir="css", sassDir="scss", imageDir="images", importPath=["bower_components/","bower_components/foundation/scss/"], javascriptsDir="js", fontsDir="fonts", relativeAssets, bundleExec, basePath="src/skin", environment="production", outputStyle="compressed", force
Individual stylesheets must be in the sass directory.
Warning: ↑ Use --force to continue.

Aborted due to warnings.
```

Downgrading back to 1.0.1 resolves the issue:

```
Running "compass:live" (compass) task
Verifying property compass.live exists in config...OK
File: [no files]
Options: httpPath="http", cssDir="css", sassDir="scss", imageDir="images", importPath=["bower_components/","bower_components/foundation/scss/"], javascriptsDir="js", fontsDir="fonts", relativeAssets, bundleExec, basePath="src/skin", environment="production", outputStyle="compressed", force
   remove src/skin/images/grids-scb6569a8d5.png
   create src/skin/images/grids-scb6569a8d5.png
   remove src/skin/images/flag-s3d430622aa.png
   create src/skin/images/flag-s3d430622aa.png
    write src/skin/css/styles.css (6.857s)

Done, without errors.
```

**Comment by sindresorhus** [comment]
@phadej

**Comment by phadej** [comment]
@adamj88 could you paste your compass gruntfile section

**Comment by phadej** [comment]
Created a probable fix. Could @mkilpatrick and @adamj88 try it out?
Post `Gruntfile` section and grunt's verbose output if it doesn't work sitll.

**Comment by thomasvankerckvoorde** [comment]
I got this error

Running "compass:dev" (compass) task
Individual stylesheets must be in the sass directory.

But @phadej his fix did the trick for me!
