### ISSUE TITLE
Support Import-once activation from options

### ISSUE THREAD

**Issue by shali3** [gruntjs/grunt-contrib-compass#236]
compass supports the [compass-import-once](https://github.com/Compass/compass/blob/master/import-once/README.md) gem since version `1.0.0.alpha.16 (12/05/2013)`.

The only way I was able to apply it with this grunt task was using the `raw` option:
```
options: {
    raw: "require 'compass/import-once/activate'"
}
```
I really think you should add support for this in the native options you provide.
Thanks :)

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt-contrib-compass#require

**Comment by shali3** [comment]
Got it. Thanks :) This worked for me:
```
options: {
    require: 'compass/import-once/activate'
}
```
