### ISSUE TITLE
grunt-contrib-compass fails with compass css3 mixins

### ISSUE THREAD

**Issue by silicakes** [gruntjs/grunt-contrib-compass#238]
## The Issue
While requesting a css3 mixin located under: 
`/Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.3/stylesheets/compass/_css3.scss`

the following error appears:
    
    Running "compass:dist" (compass) task
    error src/styles/main.scss (Line 251 of src/styles/_theme.scss: Undefined mixin 'border-image'.)
    Compilation failed in 1 files.
    Warning: ↑ Use --force to continue.

## Environment
* OS: OSX 10.10.1
* ruby -v: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
* grunt --version: grunt-cli v0.1.13 | grunt v0.4.5
* grunt-contrib-compass version: 1.0.3
* compass version: Compass 1.0.3 (Polaris)

## Gruntfile.js configuration
    compass: {
            options: {
                sassDir: 'src/styles',
                cssDir: 'dist/styles',
                generatedImagesDir: 'dist/images/generated',
                imagesDir: 'src/images',
                javascriptsDir: 'src/scripts',
                fontsDir: 'src/fonts',
                importPath: './bower_components',
                httpImagesPath: '/images',
                httpGeneratedImagesPath: '../images/generated',
                httpFontsPath: '/fonts',
                relativeAssets: false,
                assetCacheBuster: false,
                raw: 'Sass::Script::Number.precision = 10\n'
            },
            dist: {
                options: {
                    generatedImagesDir: "dist/images/generated"
                }
            }
        }

## .scss declaration
    .gradient-solid-hairline-border {
       @include base-border($border-color: $dark-secondary-color); //custom mixin, from somewhere above
       @include border-image(linear-gradient($light-green-color, $dark-secondary-color));
    }

This issue was reproduced with additional css3 styles from the aforementioned path

**Comment by MichaelKatz** [comment]
## solution
Compass has a default path through which it looks for stylesheets ones it can't find it locally.

It's possible to include files from the compass spreadsheet directory with the same syntax provided by their documentation:

    @import "compass/css3";

This should be added to grunt-contrib-compass' documentation

**Comment by terrorhawks** [comment]
Had the same issue. I managed to get it working by changing 
<code>importPath: '/bower_components'</code>
which caused a warning, but when running with force it resolved the issue.
I'm using  "grunt-force-task" to force only the compass:server task until this issue is resolved.
