### ISSUE TITLE
No error when compass-include-once is required but not installed

### ISSUE THREAD

**Issue by BendingBender** [gruntjs/grunt-contrib-compass#240]
Hi,

I have the problem that when I use the `require` option to load a plugin (`compass-include-once`) but this plugin is not installed, there is no error thrown. Instead, compass is started up without the plugin, which leads to a very unpleasant result where large files are included multiple times. For me this results in my css file growing from ~2MB to ~9MB in size.

We have a large team and it is not easy to coordinate a manual plugin installation if nothing in the build fails.

Is there a possibility to make `grunt-contrib-compass` throw an error if a specified plugin can not be found?

**Comment by sindresorhus** [comment]
What happens if you try to `require` something that isn't installed using the cli compass binary? If it also silently fails, there's nothing we can do here, and you'll have to ask in the compass issue tracker.

**Comment by BendingBender** [comment]
I'll give it a try.
