### ISSUE TITLE
Worked fine - then I get this error - only backing off to 0.9.0 fixed it. On Windows 7

### ISSUE THREAD

**Issue by httpete** [gruntjs/grunt-contrib-compass#243]
![compass_error](https://cloud.githubusercontent.com/assets/1200635/9396411/e16d7e1a-4762-11e5-8b60-5dde317e806b.PNG)

**Comment by httpete** [comment]
Note the quotes, that is what causes that command to die compass -v is fine.If I execute that without the single quotes, manually it works.

**Comment by sindresorhus** [comment]
This was fixed. https://github.com/sindresorhus/bin-version/issues/5
