### ISSUE TITLE
Changes (0px) to (0)

### ISSUE THREAD

**Issue by StephenRiosDev** [gruntjs/grunt-contrib-compass#247]
As title says, when using compass to minify files, it is removing the unit value from after zeros.  While this is ok 99% of the time, in specific instances the unit value is required.  For instance when using the value `flex: 1 0 0`, this works for all browsers except IE, which requires it to be `flex: 1 0 0px` because it does not accept unit-less values for attributes that require a unit.

**Comment by sindresorhus** [comment]
That's a Compass problem. Not this plugin.
