### ISSUE TITLE
Can't find `compass` after upgrade to newest version

### ISSUE THREAD

**Issue by deiga** [gruntjs/grunt-contrib-compass#248]
Somehow the change to locating the executable broke our Linux servers and some of our OSX desktops, I had to downgrade to make everything work again.

**Comment by driskell** [comment]
Same here.

I've located the change here: https://github.com/gruntjs/grunt-contrib-compass/commit/d0d0dcf44ee2bc8d192b7763102ff9a2d297b59d

The `whichSync` throws if `compass` is not found, which it won't be if we're using `bundle`

I'm going to try make a PR :)

**Comment by shahata** [comment]
+1

**Comment by ryuran** [comment]
+1
Works if you have a global compass installed. Doesn't work without.

**Comment by vincentorback** [comment]
I’m stilling getting this error: `Warning: not found: compass Use --force to continue.` 
Compass shouldnt have to be installed globally right?
