### ISSUE TITLE
Warning: You need to have Ruby and Compass installed and in your system path for this task to work

### ISSUE THREAD

**Issue by mxpimp47** [gruntjs/grunt-contrib-compass#66]
I am a complete noob when working with ruby and compass so please forgive me. I am trying to use grunt. I am trying to use Yeoman and I have been getting everything setup. Upon trying to run the server I get the error -

"Warning: Running "compass:dist" (compass) task
 Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue."

Then it is forced to quit. I have googled and tried reading documentation and haven't found a clear answer and solution. I found this issue - https://github.com/gruntjs/grunt-contrib-compass/issues/61 but it didnt help me. 

What am I doing wrong?

I am following this current tutorial - http://net.tutsplus.com/tutorials/javascript-ajax/building-apps-with-the-yeoman-workflow/

I apologize for my ignorance.

**Comment by frank-castro** [comment]
this fixed the issue for me "gem install compass"
