### ISSUE TITLE
Banner/Specify error when trying to use with ".min.css" script.

### ISSUE THREAD

**Issue by msguerra74** [gruntjs/grunt-contrib-compass#76]
I use the following raw option to add ".min.css" to the end of my styles, but when I try to use this in addition to the banner/specify option, it fails. I have to specify "style.css", but then it gives an error saying it's unable to read the ".css" file... because, I'm assuming it's now ".min.css".

        specify: '<%= temp %>/scss/*.scss',
        banner: '/* <%= pkg.name %> banner */'
        raw:
        'on_stylesheet_saved do |file|\n' +
        'if File.exists?(file)\n' +
        'filename = File.basename(file, File.extname(file))\n' +
        'File.rename(file, "<%= build %>/css" + "/" + filename + ".min" + File.extname(file))\n' +
        'end\n' +
        'end\n'

Hope this makes sense. Thanks!

**Comment by vladyn** [comment]
+1

**Comment by numediaweb** [comment]
Maybe the raw command can be put inside the `config.rb` as [explained here](http://h3r2on.com/2013/05/17/rename-css-on-compile.html)
